//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.trusts = new HashSet<trust>();
            this.moshtarekins = new HashSet<moshtarekin>();
        }
    
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_mozo { get; set; }
        public string book_radeseni { get; set; }
        public string book_molaf { get; set; }
        public Nullable<int> book_m_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trust> trusts { get; set; }
        public virtual moshtarekin moshtarekin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moshtarekin> moshtarekins { get; set; }
    }
}
