//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class deleted
    {
        public int deleted_id { get; set; }
        public Nullable<int> deleted_book_id { get; set; }
        public string deleted_book_name { get; set; }
        public string deleted_book_mozo { get; set; }
        public string deleted_book_radeseni { get; set; }
        public string deleted_book_molaf { get; set; }
        public Nullable<int> deleted_admin_id { get; set; }
        public string deleted_admin_user { get; set; }
        public Nullable<int> deleted_moshtarekin_id { get; set; }
        public string deleted_moshtarekin_name { get; set; }
        public string deleted_moshtarekin_family { get; set; }
        public string deleted_moshtarekin_number { get; set; }
        public Nullable<int> deleted_moshtarekin_age { get; set; }
        public string deleted_moshtarekin_codmeli { get; set; }
        public string deleted_moshtarekin_start { get; set; }
        public Nullable<int> deleted_moshtarekin_timeago { get; set; }
    }
}
