//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KetabkhoneEntities : DbContext
    {
        public KetabkhoneEntities()
            : base("name=KetabkhoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<deleted> deleteds { get; set; }
        public virtual DbSet<moshtarekin> moshtarekins { get; set; }
        public virtual DbSet<trust> trusts { get; set; }
        public virtual DbSet<updataed> updataeds { get; set; }
    }
}
