//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class moshtarekin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moshtarekin()
        {
            this.trusts = new HashSet<trust>();
            this.Books = new HashSet<Book>();
        }
    
        public int moshtarekin_id { get; set; }
        public string moshtarekin_name { get; set; }
        public string moshtarekin_family { get; set; }
        public string moshtarekin_number { get; set; }
        public int moshtarekin_age { get; set; }
        public string moshtarekin_codmeli { get; set; }
        public Nullable<System.DateTime> moshtarekin_start { get; set; }
        public Nullable<int> moshtarekin_timeago { get; set; }
        public Nullable<System.DateTime> moshtarekin_timeend { get; set; }
        public Nullable<int> moshtarekin_b_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trust> trusts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual Book Book { get; set; }
    }
}
